DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user(
    id INTEGER PRIMEARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id INTEGER UNIQUE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NOT NULL,
    body TEXT NOT NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);